name: release

on:
  release:
    types: [ released ]

permissions:
  contents: write
  packages: write

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ghcr.io/corpus-dev/mhddos_proxy, ghcr.io/corpus-dev/mhddos_proxy:${{ github.event.release.tag_name }}

  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: 'main'

      - name: Update version.txt
        run: |
          echo "${{ github.event.release.tag_name }}" > version.txt
          git config user.name "corpus-dev"
          git config user.email "corpus-dev@example.invalid"
          git add version.txt
          git diff --cached --quiet || git commit -m "Update version"
          git push
